# Cloud Build config for ingest service
# Trigger suggestion: path filter backend/** (exclude backend/processor/**)
substitutions:
  _REGION: us-east5
  _SERVICE: telemetry-ingest
steps:
  - name: gcr.io/cloud-builders/docker
    dir: backend/ingest
    args: ["build","-t","gcr.io/$PROJECT_ID/${_SERVICE}:$COMMIT_SHA","."]
  - name: gcr.io/cloud-builders/docker
    args: ["push","gcr.io/$PROJECT_ID/${_SERVICE}:$COMMIT_SHA"]
  # Optional deploy step (remove if using Cloud Run's source deploy separately)
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy ${_SERVICE} \
          --image gcr.io/$PROJECT_ID/${_SERVICE}:$COMMIT_SHA \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars TOPIC=telemetry-raw \
          --set-env-vars API_KEY=$$API_KEY
    secretEnv: [API_KEY]
images:
  - gcr.io/$PROJECT_ID/${_SERVICE}:$COMMIT_SHA
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/telemetry-api-key/versions/latest
      env: API_KEY
