## Cloud Build config for INGEST service (receives extension HTTP posts -> Pub/Sub publish)
## Create a trigger with: included files filter backend/ingest/** (and this file)
## Standardizes deployment & ensures consistent TOPIC env.
substitutions:
  _REGION: us-east5
  _SERVICE: telemetry-ingest
  _TOPIC: telemetry-data
steps:
  - name: gcr.io/cloud-builders/docker
    dir: backend/ingest
    args: ["build","-t","gcr.io/$PROJECT_ID/${_SERVICE}:$COMMIT_SHA","."]
  - name: gcr.io/cloud-builders/docker
    args: ["push","gcr.io/$PROJECT_ID/${_SERVICE}:$COMMIT_SHA"]
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        echo "Deploying ${_SERVICE} (topic=${_TOPIC}) to region ${_REGION}" 
        gcloud run deploy ${_SERVICE} \
          --image gcr.io/$PROJECT_ID/${_SERVICE}:$COMMIT_SHA \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars TOPIC=${_TOPIC},API_KEY=$$API_KEY
    secretEnv: [API_KEY]
images:
  - gcr.io/$PROJECT_ID/${_SERVICE}:$COMMIT_SHA
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/telemetry-api-key/versions/latest
      env: API_KEY
